Feature/issue 19/implement application context
bobocode-blyznytsia/bring-framework pull request #37
Opened 2023-02-03 22:51 UTC by marynamelnichuk

## Describe your changes

ApplicationContext is a central part of the framework. It holds the bean definitions, instantiated beans, bean definition readers, bean factory. It is the entry point for the framework user.

## Issue #19

## Checklist before requesting a review
- [X] There are no MR remarks
- [X] Clean and concise code that is easy to read and understand
- [X] Code covered with tests and they are green
- [X] Code API has informative JavaDoc on it
- [X] Rich logging with detailed messages and correct use of log levels

2023-02-06 18:33 UTC, Serhiiilnytskyi approved these changes

2023-02-06 19:39 UTC, vitshch requested changes

2023-02-06 19:39 UTC, vitshch commented on src/main/java/com/bringframework/context/AnnotationConfigApplicationContext.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> (T) entry.getValue()));
You can do `entry -> beanType.cast(entry.getValue())`

2023-02-07 05:54 UTC, vitshch approved these changes

2023-02-07 07:35 UTC, merged